# A Helm Chart for an IOC instance
apiVersion: v2
name: ioc-instance

version: 1.0.0

# When we deploy with the edge-containers-cli we override this on the command line.
# Direct deployment with Helm will use the default beta value.
appVersion: 0.0.1b1

type: application

dependencies:
  - name: configmap
    version: "1.0.0"
    repository: file://../../helm/configmap
  - name: beamline
    version: "1.0.0"
    repository: file://../../helm/beamline
