# yaml-language-server: $schema=https://github.com/epics-containers/ioc-adsimdetector/releases/download/2024.1.1/ibek.ioc.schema.json
ioc_name: "{{ ioc_yaml_file_name }}"

description: Example simulated camera for BL47P

entities:
  - type: epics.EpicsCaMaxArrayBytes
    max_bytes: 3000000

  - type: devIocStats.iocAdminSoft
    IOC: "{{ ioc_name | upper }}"

  - type: ADSimDetector.simDetector
    PORT: DET.DET
    P: BL47P-EA-TST-01
    R: ":DET:"
    WIDTH: 600
    HEIGHT: 1024

  - type: ADCore.NDPvaPlugin
    PORT: DET.PVA
    PVNAME: BL47P-EA-TST-01:PVA:OUTPUT
    P: BL47P-EA-TST-01
    R: ":PVA:"
    NDARRAY_PORT: DET.DET
