apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
data:

{{- /*
  add the contents of every file in the config folder of this IOC helm chart
  into the config map - The files must be text only.
*/ -}}

{{ (.Files.Glob "../../*").AsConfig | indent 2 }}
