---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ .Release.name }}-config
  labels:
    app: {{ .Values.ioc_name }}
data:

{{- /*
  add the contents of every file in the config folder of this IOC helm chart
  into the config map - The files must be text only.
*/ -}}

{{ (.Files.Glob "../../config/*").AsConfig | indent 2 }}
