apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
data:

# ---- contents of the ioc instance config folder ----------------------------
{{ (.Files.Glob "services/bl47p-ea-test-01/config/**").AsConfig | indent 2 }}